### ISSUE TITLE
Unordered list not rendering as bullets on site pages

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#290]
I created the following page: http://staging.denverchildrenscorridor.org/en/policies/

Part of the text in "Floodlight Community Values" is formatted as a list using the <ul> tag, and shows up as a bulleted in the Django admin. But on the page itself, it isn't formatted as such.

The everything page has how bulleted lists should appear: https://docs.google.com/file/d/0B1CQ7Qy70V50aHA5eS1ZdlpBTzA/edit

**Comment by patternleaf** [comment]
this should be fixed when next the staging site is updated. also there are now classes for pullquotes, if they're ever needed:

``` html
<p class="pullquote">lorem ipsum...</p>
```

will style as pullquote floated left and 

``` html
<p class="pullquote right">lorem ipsum...</p>
```

will pullquote to the right.

**Comment by jwirfs-brock** [comment]
Great. And just double-checking, will we have ordered lists working as well?

**Comment by ghing** [comment]
@jwirfs-brock This is deployed on staging and I'm seeing the bullets.  I'll close this.  Reopen and assign to @patternleaf if something still isn't right.
