### ISSUE TITLE
When adding a "connected" story, see "Image and Text" section heading, but no way to edit/delete

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#601]
When you add a connected story, the simplified version of the editor doesn't have the section tile ("Image and Text" for a photovoice story). So you can't delete or edit it. But when you preview a story, you see "Image and Text" appear as the section title.

I'm not sure if this is an issue with the connected story/photovoice template, or if this is an issue with how the simplified version of the Story Builder was set up to work with connected stories.

Here's what the connected story builder looks like:
![connected_story_builder](https://f.cloud.github.com/assets/1020518/115696/7cddb062-6bd9-11e2-874b-e215dbc39f21.png)

And here's what the preview looks like:
![connected_story_preview](https://f.cloud.github.com/assets/1020518/115697/8331fca2-6bd9-11e2-9098-469ba7e45655.png)

**Comment by ghing** [comment]
This is either a bug with the viewer or the builder depending on how you look at it.  Either the viewer should not show section titles for connected stories, or the builder should remove the section title from the template behind the scenes.  Either way, it's not a very difficult fix.

**Comment by ghing** [comment]
I was looking through the code and saw that section titles should be hidden for connected stories.  That's when I realized that the problem is that the preview link goes to a view that real users should never actually see. 

The specification for connected stories is that they should be shown at the end of their seed story.  So, the preview link in the viewer should point to the story within the viewer of the seed story, not to it's own viewer.

**Comment by ghing** [comment]
@jwirfs-brock I believe I've addressed this issue as of 9a4ecd0.  I've deployed these changes to staging.  Can you verify that this is fixed for the case that produced the error?

**Comment by jwirfs-brock** [comment]
@ghing I'm still seeing the "Image and Text" header in a published connected story. See: http://staging.floodlightproject.org/en/stories/testing-connected-story-fixes/

**Comment by ghing** [comment]
@jwirfs-brock I think the problem is that you're viewing the aforementioned story in story viewer by itself rather than in the seed story's viewer.  The "Image and Text" header does not seem to be present when viewing the story through the [seed story's viewer](http://staging.floodlightproject.org/en/stories/planting-peace-in-whittier/viewer/) (or jumping directly to the connected story in the [seed story's viewer](http://staging.floodlightproject.org/en/stories/planting-peace-in-whittier/viewer/#connected-stories/bac1b674abb74257bb8d9ebd3fbff74a)

Can you check whether the story shows up without the default section header when being viewed through the seed story's viewer and when clicking the "Preview" link when editing the connected story in the builder?

A connected story is stored in the database in the same way as any other story which is why it's possible to view it in the story viewer by itself.  While the paths to the story detail page and viewer work for a connected story, they shouldn't ever be exposed to end users.

**Comment by jwirfs-brock** [comment]
@ghing Got it! Looks good when viewing in the preview and from the seed
story viewer.

**Comment by jwirfs-brock** [comment]
@ghing Looks like we can close this one.
