### ISSUE TITLE
Strange behavior when dragging an image from the asset drawer

### ISSUE THREAD

**Issue by jwirfs-brock** [denverfoundation/storybase#746]
Roughly following the test script with some modifications, I did these steps:
- Given the user inputs "http://www.strivenetwork.org/sites/default/files/images/map_4_15_UWW_nostars.png" in the "Enter image URL" field
              Given the user clicks the "Save Changes" button
- Then the image "http://www.strivenetwork.org/sites/default/files/images/map_4_15_UWW_nostars.png" is visible
- Given the user changes the layout to "Above/Below"
- Then the text "You removed an asset, but it's not gone forever" is present
- Given the user drags the image "hhttp://www.strivenetwork.org/sites/default/files/images/map_4_15_UWW_nostars.png" from the asset drawer to the "top" container
- Then the image "http://www.strivenetwork.org/sites/default/files/images/map_4_15_UWW_nostars.png" is visible

The test worked fine until the "user drags the image...to the 'top' container" step.

At this stage, I noticed:
- I did not see the "ghost image" as I was dragging/dropping (as expected)
- Instead of appearing on the top section, the image appeared on the bottom

After this, I clicked the "remove asset" icon and saw the "your asset is not gone forever..." message, but observed that the image asset was still showing up in the bottom container.

See screenshot:
![screen shot 2013-05-08 at 11 33 44 am](https://f.cloud.github.com/assets/1020518/478236/5281829a-b7f5-11e2-9394-44e28845b189.png)

Then when I clicked the "remove asset" icon again, I got an "error removing asset" message.

See screenshot:
![screen shot 2013-05-08 at 11 38 37 am](https://f.cloud.github.com/assets/1020518/478238/6379cf44-b7f5-11e2-94f7-bb30df84947b.png)

When I refreshed the builder, everything appeared as expected.

**Comment by ghing** [comment]
Updated title to reflect that this issue also affects uploaded assets as well as URL-based assets.

**Comment by ghing** [comment]
Update: Also, when dragging an asset, the contents of the asset drawer is blanked out.

**Comment by jwirfs-brock** [comment]
@ghing This seems to be working fine. 

One thing I did notice, though, is that when I...
- Had the asset drawer open
- Removed an asset

The asset did not immediately appear in the asset drawer. When I closed the asset drawer and reopened it, the asset appeared in the drawer as expected.

However, I wasn't able to reproduce this, so I am not sure exactly what conditions caused it (I should have been recording my screen!).

**Comment by jwirfs-brock** [comment]
I was able to replicate the behavior and create a narrated screen capture of it:
http://www.youtube.com/watch?v=AU6BOzMnhXI&feature=youtube_gdata_player

The steps I did were:
- Create a new story (and give it a title, byline, and summary)
- Add an image (from URL) to Untitled Section
- Change the Untitled Section from One-Up to Side-by-Side layout
- Open asset drawer
- Drag image asset from the asset drawer to the left container
- Delete the image asset

Expected behavior:
- Would see "your asset has been removed message"
- Asset would appear in asset drawer

Actual behavior:
- Saw no message
- Asset did not appear until I closed and then re-opened the drawer

I was using Chrome.

**Comment by ghing** [comment]
@jwirfs-brock Good catch.  I did all my testing in a situation with multiple assets, so never ran into this behavior.

I fixed the "Asset did not appear until I closed and then re-opened the drawer".  I wasn't able to replicate the "Saw no message" behavior.  My only thought is that we squash duplicate alert messages, so, in the scenario described above, if you remove the asset from the container while the alert message triggered by the layout change is still present (but maybe totally faded out but not quite yet removed) you won't see a second "Your asset has been removed" message. 

Can you re-test and tell me what you find?

**Comment by jwirfs-brock** [comment]
Oops, I tested this yesterday and commented it on it. I must have forgot to hit comment or something...

This looks good now. I am still seeing (or not seeing, rather) the missing message in a few cases, but I a having trouble consistently replicating it. @ghing I think you are probably right about if having something to do with an earlier message not completely fading out yet -- it's actually there for a long time.

I think, however, that most users that encounter this will be fine. Closing...
